# Generated by Django 4.0.3 on 2022-04-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alllisting_bid_closedbid_comment_listing_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category1',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='category2',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
