# Generated by Django 4.0.3 on 2022-04-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_category1_listing_categorys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='video',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
